name: CI/CD Workflow

on:
  push:
    branches:
      - main  # Trigger workflow on pushes to main branch
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Build and start Docker Compose services
      - name: Build and start services
        run: docker-compose up -d --build

      # Step 4: Test the service with curl
      - name: Test the service
        run: |
          # Wait for the service to start
          sleep 10
          # Check if the service is running and responding
          curl -f http://localhost:7270 || exit 1
          curl -f http://localhost:7270/health || exit 1
          curl -f http://http://localhost:7270/#/labels || exit 1

      # Step 5: Tear down services
      - name: Tear down Docker Compose
        if: always()
        run: docker-compose down
