---

  name: CI/CD Workflow
  
  on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
  
  jobs:
    build-and-test:
      runs-on: ubuntu-latest
  
      steps:
        # Step 1: Checkout the code
        - name: Checkout repository
          uses: actions/checkout@v3
  
        # Step 2: Set up Docker
        - name: Set up Docker
          uses: docker/setup-buildx-action@v2
  
        # Step 3: Build and start Docker Compose services
        - name: Build and start services
          run: docker-compose up -d --build
  
        # Step 4: Debug Docker Compose Logs
        - name: Debug Docker Compose Logs
          run: docker-compose logs
  
        # Step 5: Wait for Service to Be Ready
        - name: Wait for Service to Be Ready
          run: |
            for i in {1..10}; do
              curl -f http://recipesage_api:7270 && break || sleep 5;
            done
  
        # Step 6: Test the service with curl
        - name: Test the service
          run: |
            curl -f http://recipesage_api:7270 || exit 1
            curl -f http://recipesage_api:7270/health || exit 1
            curl -f http://recipesage_api:7270/#/labels || exit 1
  
        # Step 7: Tear down services
        - name: Tear down Docker Compose
          if: always()
          run: docker-compose down
  